version: '2'
services:
  ubuntu-16-nginx-1.10.0-php-5.6-zend-2:
    build: .
    image: ubuntu-16-nginx-1.10.0-php-5.6-zend-2:latest
    ports:
      - "8080:8080"
    user: "100000"
    environment:
      SUPERVISORD_LOGLEVEL: debug
